LochanDesigns/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('products/', include('storage.urls', namespace='storage')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('contact/', views.contact_page, name='contact'),
    path('login/', views.login_page, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.register_page, name="register"),
    path('', views.home_page, name='home'),
] 
urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(null=True, blank=True, upload_to='media/')

    def __str__(self):
        return f'{self.product_name}'

class ProductInventory(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    created_at = models.TimeField()
    modified_at = models.TimeField()
    deleted_at = models.TimeField()

    def __str__(self):
        return f'{self.product} {self.quantity}'

frontend/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django.forms import ClearableFileInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core import validators

class ContactForm(forms.Form):
	first_name = forms.CharField(max_length = 50)
	last_name = forms.CharField(max_length = 50)
	email_address = forms.EmailField(max_length = 150)
	message = forms.CharField(widget = forms.Textarea, max_length = 2000)
	botcatcher = forms.CharField(required=False,
								widget=forms.HiddenInput,
								validators=[validators.MaxLengthValidator(0)])
	def __init__(self, *args, **kwargs):
		super(ContactForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_class = 'form-horizontal'
		self.helper.label_class = 'label label-default text-light'
		self.helper.field_class = 'form-control'
		self.helper.layout = Layout(
			'first_name',
			'last_name',
			'email_address',
			'message',
			'botcatcher',
			Submit('submit', 'Submit', css_class='btn btn-secondary')
		)

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1']

frontend/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.core.mail import send_mail, BadHeaderError
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import ContactForm, CreateUserForm
from .models import *
from storage.models import Storage

def home_page(request):
	storageRecord = Storage.objects.order_by('?')[:1]
	bg = storageRecord
	return render(request, 'main.html', {'bg':bg})

def contact_page(request):
	storageRecord = Storage.objects.filter(product_name='Background')
	bg = storageRecord
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			subject = "Website Inquiry" 
			body = {
			"First Name: " + form.cleaned_data['first_name'], 
			"Last Name: " + form.cleaned_data['last_name'], 
			"Email: " + form.cleaned_data['email_address'], 
			"Message: " + form.cleaned_data['message'], 
			}
			message = "\n".join(body)
			try:
				send_mail(subject, message, 'haley@lochandesigns.com', ['haley@lochandesigns.com', 'jlochan53@gmail.com'])
			except BadHeaderError:
				return HttpResponse('Invalid header found.')
			return render(request, "contact.html",{'form':form, 'successful_submit': True, 'bg': bg})
		else:
			return render(request, "contact.html", {'form':form, 'bg': bg})

	form = ContactForm()
	return render(request, "contact.html", {'form':form, 'bg': bg})

def register_page(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		form = CreateUserForm()

		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)
				return redirect('login')

		context = {'form':form}
		return render(request, "register.html", context)

def login_page(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password = request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('/')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, "login.html", context)

def logout_user(request):
	logout(request)
	return redirect('login')

templates/contact.html
{% extends 'main.html' %}
{% block content %}
{% load crispy_forms_tags %}
<style>
  .errorlist {
    color: #ba3939;
    background: #ffe0e0;
    border: 0px solid #a33a3a;
  }
  #success {
    /* color: #88B04B; */
    color: #d3af9c;
    font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
    font-weight: 900;
    font-size: 40px;
    margin-bottom: 10px;
  }
  body {
    text-align: center;
    background: #EBF0F5;
  }
  i {
    /* color: #9ABC66; */
    color: #d3af9c;
    font-size: 100px;
    line-height: 200px;
    margin-left:-5px;
  }
  label {
    justify-content: center;
    font-family: 'Courier New', Courier, monospace;
    color: #fff;
    text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);
  }

</style>
{% if successful_submit %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#exampleModal").modal('show');
            $('#id_first_name').val("");
            $('#id_last_name').val("");
            $('#id_email_address').val("");
            $('#id_message').val("");
        });
    </script>
{% endif %}
<script type="text/javascript">
    $(document).ready(function(){
        console.log("hello world");
    });
</script>

<p>{{ form.errors }}</p>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Message Sent Succesfully!</h5>
          <button type="button" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <div class="card-transparent">
                <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
                  <i class="checkmark">✓</i>
                </div>
                  <h1 id="success">Success</h1> 
                  <p class="text-black">We received your email request and<br/> we'll be in touch shortly!</p>
                </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

<h1>Contact</h1>
<p id="home_p1">
    Please submit the form below for purchase or custom inquiries!
</p>
<div class="container col-lg-12 block">
    <div class="row col-xs-6 block2 center">
        <form class="form-horizontal" align="center" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
</div>
<br>
{% endblock %}

templates/footer.html
{% if request.get_full_path == '/' %}
<div class="text-center">
    © 2022 Copyright
</div>
{% else %}
{% endif %}

templates/home.html
{% block content %}
<style>
    body {
        text-align: center;
        background: #EBF0F5;
    }
</style>
<div id="center" class="text-center cover-container">
    <div class="inner cover">
        <h1 id="home_h1">Welcome to Lochan Designs</h1>
        <p id="home_p1">Artist </p>
        <p id="home_p1" style="font-size:xx-large;">Haley Lochan </p>
    </div>
</div>

{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
            font-family: serif;
            background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3));
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #fafafa;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: rgb(0, 0, 0);
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
                {% for message in messages %}
                <p id="messages">{{ message }}</p>
                {% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'storage:products' %}" class="ml-2">Go to the Art Gallery</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

</html>

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    {% load static %}
    <style>
        h1, h4 {
            justify-content: center;
            font-family: 'Courier New', Courier, monospace;
            color: #fff;
            text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);
        }

        #home_h1, #home_p1 {
            justify-content: center;
            font-family: 'Courier New', Courier, monospace;
            color: #fff;
            text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);
        }

        #center {
            margin: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        #logo {
            padding: 0;
            text-align: left;
            font-size: 23px;
            line-height: 26px;
            letter-spacing: 5px;
            font-weight: 200;
        }
        nav {
            font-family: 'Red Hat Text', Sans-Serif;
            font-weight: 200;
            color: #303030;
        }
        #footer {
            font-family: 'Red Hat Text', Sans-Serif;
            font-weight: 200;
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 2.5rem;
            color: #fff;
        }
    </style>
    {% for bg in bg %}
    <style>
        .bg {
            height: 100%;
            width: 100%;
            position: absolute;
            background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), 
                        url('{{ bg.image.url }}') no-repeat ;
            background-size: 100% 100%;
        }
    </style>
    {% endfor %}
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.1.slim.min.js" integrity="sha256-w8CvhFs7iHNVUtnSP0YKEg00p9Ih13rlL9zGqvLdePA=" crossorigin="anonymous"></script>
    <title>Lochan Designs</title>
</head>
{% if request.path != '/products/' %}
<div class="bg">
{% else %}
<div>
{% endif %}
    {% include 'navbar.html' %}

    <div class="container card-body">
        {% block content %}

        {% if request.path == '/' %}
            {% include 'home.html' %}
        {% endif %}

        {% endblock %}
    </div>
</div>
{% if request.get_full_path == '/' %}
<footer id="footer" class="navbar-static-bottom text-center navbar-light text-lg-start">
    {% include 'footer.html' %}
</footer>
{% else %}
{% endif %}
</html>

templates/maintenance/edit_record.html
{% extends 'main.html' %}
{% block content %}
{% load crispy_forms_tags %}

<form method="POST" action="">
  {% csrf_token %}
  {% crispy form %}
</form>
{% endblock %}

templates/maintenance/maintenance.html
{% extends 'main.html' %}
{% block content %}
<h3>Edit Gallery</h3>

<!-- Products -->
<div class="row">
  {% for product_inv in storage_records %}
  <div class="col-lg-4">
    <div class="card border-0">
      <a href="{% url 'storage:edit_record' product_inv.id %}">
        <img class="rounded thumbnail mx-auto" style="width: 18rem; height: 20rem;" src="{{ product_inv.image.url }}" alt="connect">
      </a>
      <div class="card-body mx-auto">
        <h5 class="card-title">{{ product_inv.product_name }}</h5>
        <a href="{% url 'storage:edit_record' product_inv.id %}" class="btn btn-primary">Edit</a>
        <a href="{% url 'storage:delete_record' product_inv.id %}" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/maintenance/upload.html
{% extends 'main.html' %}

{% block content %}
{% load crispy_forms_tags %}
<h3>Upload Photo</h3>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}

    <button class="btn btn-primary" type="submit">Save</button>
</form>


{% endblock %}

templates/navbar.html
{% if request.get_full_path == '/' or request.get_full_path == '/contact/' %}

<nav class="navbar navbar-expand-lg navbar-dark shadow-5-strong">
{% else %}
<nav class="navbar navbar-expand-lg navbar-light shadow-5-strong">
{% endif %}
<style>
  /* #hello {
    font-size: 18px;
    margin-right: 20px
  } */
</style>
  <div class="container-fluid">
    {% load static %}
    <!-- <a id="logo" class="navbar-brand" href="{% url 'home' %}">LochanDesigns Gallery</a><img class="rounded" id="logo" src="{% static '/logo.png' %}" height="32" alt="Logo"></a> -->
    <a id="logo" class="navbar-brand" href="{% url 'home' %}">LochanDesigns</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Tognavigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" id="hello" aria-current="page">Hello, {{ request.user }}</a>
        </li>
        {% else %}
        {% endif %}
        {% if request.user.is_superuser %}
        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Maintenance
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'storage:upload' %}">Upload Photo</a></li>
            <li><a class="dropdown-item" href="{% url 'storage:edit' %}">Edit Gallery</a></li>
          </ul>
        </li>
        {% else %}
        {% endif %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'storage:products' %}">Gallery</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'contact' %}">Contact Us</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/products.html
{% extends 'main.html' %}
{% block content %}

<!-- Products -->
<div class="row">
  {% for product_inv in page_obj %}
  <div class="col-lg-4">
    <div class="card border-0">
      <img class="rounded thumbnail mx-auto" style="width: 18rem; height: 20rem;" src="{{ product_inv.image.url }}" alt="connect">
      <div class="card-body mx-auto">
        <h5 class="card-title">{{ product_inv.product_name }}</h5>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<!-- Pagination  -->
<nav aria-label="..." class="">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">First</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
    </li>
    {% endif %}

    <!-- Active Page -->
    <li class="page-item active" aria-current="page">
      <a class="page-link" href="#">{{ page_obj.number }}</a>
    </li>

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    </li>
    {% endif %}
  </ul>
</nav>

{% endblock %}

templates/register.html
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
            font-family: serif;
            background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3));
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #ffffff;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: rgb(0, 0, 0);
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.username }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{ form.email }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password1 }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2 }}
						</div>
				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
                {{ form.errors }}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';

		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>